---
supported_pg_version: 15
deployment_type: "galaxy"
_postgres_image: quay.io/sclorg/postgresql-15-c9s:latest

custom_resource_key: '_galaxy_ansible_com_galaxyrestore'

backup_api_version: 'v1beta1'
backup_kind: 'GalaxyBackup'

# If set to true, the restore process will delete the existing database and create a new one
force_drop_db: false
pg_drop_create: ''

is_k8s: false
is_openshift: false

db_secret_exists: false
