---
- k8s_status:
    api_version: "{{ api_version }}"
    kind: "{{ kind }}"
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    conditions:
      - type: "{{ deployment_type|capitalize }}-API-Ready"
        message: Creating token authentication Secret
        reason: CreatingTokenAuthSecret
        status: "False"
        lastTransitionTime: "{{ lookup('pipe', 'date --iso-8601=seconds') }}"

- name: Generate token private authentication key
  community.crypto.openssl_privatekey:
    path: /tmp/private_key.pem
    type: ECC
    curve: secp256r1

- name: Generate token public authentication key
  community.crypto.openssl_publickey:
    path: /tmp/public_key.pem
    privatekey_path: /tmp/private_key.pem

- name: Create token authentication secret
  k8s:
    apply: true
    definition: "{{ lookup('template', 'pulp-container-auth.secret.yaml.j2') }}"

- name: Remove token authentication keys
  ansible.builtin.file:
    path: '/tmp/{{ item }}_key.pem'
    state: absent
  loop:
    - private
    - public

- name: Remove ownerReferences from token authentication secret to avoid garbage collection
  k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: '{{ container_token_secret }}'
        namespace: '{{ ansible_operator_meta.namespace }}'
        ownerReferences: null
  no_log: "{{ no_log }}"

- name: Get container token configuration
  k8s_info:
    kind: Secret
    namespace: '{{ ansible_operator_meta.namespace }}'
    name: '{{ container_token_secret }}'
  register: _container_token_configuration
  no_log: "{{ no_log }}"
